name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'  # Only trigger on changes to files in docs directory
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./docs/package.json

      - name: Install dependencies
        run: cd docs && pnpm install --frozen-lockfile

      - name: Build website
        run: cd docs && pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
